package ch.so.agi.ili2meta.model;

public enum DataType {
    TEXT, MTEXT, JSON_TEXT, INTEGER, DOUBLE, DATE, DATETIME, ENUMERATION, POLYGON, LINESTRING, POINT, MULTIPOLYGON, MULTILINESTRING, MULTIPOINT, STRUCTURE, UNDEFINED  
}
